[package]
name = "tls_server_client"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
rustls = "0.23.25"
webpki-roots = "0.26.8"
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.26.2"
